import type { Metadata } from "next";
import "../styles/index.scss";
import { StoreProvider } from "./redux/provider";
import { store } from "./redux/store";
import { getEmployeesAction } from "./redux/employeeAction";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  await store.dispatch(getEmployeesAction());
  const { employee } = store.getState();

  return (
    <html lang="en">
      <body>
        <StoreProvider
          preloadedState={{
            employee,
          }}
        >
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
